<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>P0-dashboard-headline</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>10</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>0c35d16d-c7dd-45c7-ba70-4a4440588034</testSuiteGuid>
   <testCaseLink>
      <guid>ca180b97-0cdc-4fdc-94c8-8092c64993e8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/team topads/sellerapp/dashboard/headline/MTCM-115557-as a seller, i can not input headline name when name is wrong</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>288fab35-6ef8-4653-8e34-368f60b96295</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>962f134a-b94c-4d50-9f3a-90cc1b2fe944</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>793ae979-211b-4373-9cbc-e7b80e928295</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>31f02534-aa5b-4092-ab3c-cdc1506cb117</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9234d95c-46e0-4a68-b137-372d4bad336a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ebbcc538-0113-4f14-9dfb-219f459a9124</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>false</value>
         <variableId>3feea77b-64f5-4f83-b8b9-e0135845dd17</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>202014e5-0b18-4204-8428-d2d1277647e9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5ec0339b-482a-495a-aca3-3d5cc9a397cb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/team topads/sellerapp/dashboard/headline/MTCM-115567-as a seller, i can see success message after create headline ads</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b2b7e0e6-e2bc-44e4-a9e1-d9656dec8036</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f85f5698-5265-4c74-abef-0ec822e04c62</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2b1a487f-6c0d-4b92-a8ea-3960aac50422</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>da5286a4-1373-40e2-aa7c-8ca8811b6e34</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>false</value>
         <variableId>434dbefd-70d7-4899-affa-72e8d47460d9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9d251dd5-ed2e-44cc-8928-fbf4b745c12d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>eef5f7ce-eab2-4f30-85b8-8b3787b537d2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/team topads/sellerapp/dashboard/headline/MTCM-115559-as a seller, i can not create headline when promotional message is wrong</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9a252e4c-549c-46df-853f-705374cc0796</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>288fab35-6ef8-4653-8e34-368f60b96295</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>962f134a-b94c-4d50-9f3a-90cc1b2fe944</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>793ae979-211b-4373-9cbc-e7b80e928295</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>27872cf1-e8bd-4120-9c61-30d675a51f97</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>31f02534-aa5b-4092-ab3c-cdc1506cb117</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>false</value>
         <variableId>e056170b-67c4-443f-9964-226f44fc5c9d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>75f0739c-765e-43bf-9801-89bc319eac77</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/team topads/sellerapp/dashboard/headline/MTCM-115550-as a seller, i can delete Iklan Toko</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>987cee37-2647-40b7-ba13-04906dd50950</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>288fab35-6ef8-4653-8e34-368f60b96295</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>962f134a-b94c-4d50-9f3a-90cc1b2fe944</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>793ae979-211b-4373-9cbc-e7b80e928295</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>false</value>
         <variableId>852b4487-f59d-4d07-937f-34dc4b161abd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ac382e42-97b2-4b9c-bc0a-58cc3f472c56</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/team topads/sellerapp/dashboard/headline/MTCM-115552-as a seller, i can bulk delete Iklan Toko</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>04a0293d-0cf8-4fc9-8f3e-b9d3b25fb6c3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>288fab35-6ef8-4653-8e34-368f60b96295</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>962f134a-b94c-4d50-9f3a-90cc1b2fe944</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>793ae979-211b-4373-9cbc-e7b80e928295</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>false</value>
         <variableId>2c0edc37-d028-44ae-8408-1f19456f8228</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a91ca146-9936-45b7-bc30-4a9ec897ea0e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/team topads/sellerapp/dashboard/headline/MTCM-115549-as a seller, i can change status Iklan Toko</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9a252e4c-549c-46df-853f-705374cc0796</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>288fab35-6ef8-4653-8e34-368f60b96295</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>962f134a-b94c-4d50-9f3a-90cc1b2fe944</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>793ae979-211b-4373-9cbc-e7b80e928295</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>false</value>
         <variableId>e056170b-67c4-443f-9964-226f44fc5c9d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e55f8707-15d9-430a-8bf4-870024484166</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/team topads/sellerapp/dashboard/headline/MTCM-115570-as a seller, i can bulk change status Iklan Toko</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9a252e4c-549c-46df-853f-705374cc0796</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>288fab35-6ef8-4653-8e34-368f60b96295</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>962f134a-b94c-4d50-9f3a-90cc1b2fe944</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>793ae979-211b-4373-9cbc-e7b80e928295</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>false</value>
         <variableId>e056170b-67c4-443f-9964-226f44fc5c9d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>112035f0-281c-4b3e-93d7-6d1ac215d908</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/team topads/sellerapp/dashboard/headline/MTCM-115551-as a seller, i can change status Iklan Toko from detail Iklan Toko</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9a252e4c-549c-46df-853f-705374cc0796</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>288fab35-6ef8-4653-8e34-368f60b96295</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>962f134a-b94c-4d50-9f3a-90cc1b2fe944</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>793ae979-211b-4373-9cbc-e7b80e928295</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>false</value>
         <variableId>e056170b-67c4-443f-9964-226f44fc5c9d</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
